f = open("austen.txt", 'r', encoding='utf8')

text = f.read()

text = text.replace("\n", " ")
text = text.replace(",", "")
text = text.replace(".", "")
text = text.replace("!", "")
text = text.replace("?", "")
text = text.replace("-", " ")
text = text.replace("_", "")
text = text.replace("&", "and")
text = text.replace("æ", "ae")
text = text.replace("(", "")
text = text.replace(")", "")
text = text.replace("[", "")
text = text.replace("]", "")
text = text.replace("{", "")
text = text.replace("}", "")
text = text.replace("/", " ")
text = text.replace(":", " ")
text = text.replace(";", " ")
text = text.replace("*", "")
text = text.replace("\"", "")
text = text.replace("\'", "")
text = text.replace("^", "")
text = text.replace("£", "pounds")
text = text.replace("½", "1/2")
text = text.replace("à", "a")
text = text.replace("á", "a")
text = text.replace("è", "e")
text = text.replace("é", "e")
text = text.replace("ê", "e")
text = text.replace("“", "")
text = text.replace("”", "")

print(text[0:100])

with open("austen2.txt", 'w') as fobj:
    fobj.write(text)